wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1644917787
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      3:
      - 2
      - 16
      4: 3.9.0
      5: 0.12.10
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 30
epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.001
